@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.moderngamingworlds_mods.woodenutilities.common.menu.slot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;