@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.moderngamingworlds_mods.woodenutilities.common.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;