@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.moderngamingworlds_mods.woodenutilities.common.item.buckets;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;